### ISSUE TITLE
Keeping python versions as floats is ugly

### ISSUE THREAD

**Issue by KOLANICH** [rocky/python-uncompyle6#158] opened 2018-02-21 21:36 UTC
I guess it's better to use tuples.

**Comment by rocky** [comment] 2018-02-22 17:09
Like your other issue, while I understand and appreciate your intent and applaud your desire to improve uncompyle6, the description is vague to the point of not being actionable, and possibly the ideas or understanding a little fuzzy.

Define "ugly". 

And tuples is a vague word. Do you mean the tuple you get back from `sys.version_info`? Here is an example: 

```
>>> tuple(sys.version_info)
(3, 6, 3, 'final', 0)
>>> sys.version_info
sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

One thing to note is that this is not entirely a tuple of ints which makes comparing two of these a little difficult: Is the above before or after a tuple that has "release-candidate" instead of "final"? 

So maybe you mean the first 3 items? While those are ints, it really doesn't capture the level of change in bytecode without further mapping. 

The most precise discrimination of  what variation of bytecode that is used would in fact be the magic number associated with the interpreter, e.g. `imp.get_magic()` (deprecated) or `importlib.util.MAGIC_NUMBER`. 

While more precise, I am sure that might be considered "uglier" by some as it is something like `b'3\r\r\n'`.

Also, I probably disagree with the characterization that floats as used here ugly. I use "probably" because you haven't expressed by what you mean by ugly. 

```
if my_version < 2.7:
```

is not less "ugly" or any less clear in my opinion than: 

```
if my_version < (2, 7):
```

Finally, I should note that some routines like `scanner.get_scanner()` allows a string as well as a float. 

RIght now uncompyle6 doesn't handle all bytecode that was ever used by a python interpreter, just a largish set of the released bytecode. If someday in the future uncompyle6 wants to handle the interim versions then yes, float won't work. But until then there's no problem with using it now. 

Unless you can make a stronger case, and describe in more detail what the problem is and why floats are less desirable I'm tempted to close this issue.

**Comment by KOLANICH** [comment] 2018-02-23 10:35
>Define "ugly".

Floats were not intended to store version numbers which are usually integers. Floats have some drawbacks like dealing with epsilon (even though we will likely never have problems with it). It disallows easy access to major and minor. The only advantage of floats is their literal notation with dot, but even it fails since there are multiple dots in versions. That's why using floats for versions is ugly.

>So maybe you mean the first 3 items?

I meant this.
>While those are ints, it really doesn't capture the level of change in bytecode without further mapping.

>The most precise discrimination of what variation of bytecode that is used would in fact be the magic number associated with the version of Python used to compile the code, e.g. imp.get_magic() (deprecated) or importlib.util.MAGIC_NUMBER.

Haven't known that.

>While more precise, I am sure that might be considered "uglier" by some as it is something like b'3\r\r\n'.

IMHO magic numbers are ugly themselves. But since we have to deal with them, we have to deal with them. I guess we may use the first 2 bytes of it converted to an integer since the second 2 bytes are `\r\n`.

**Comment by rocky** [comment] 2018-02-23 12:55
Thanks for the clarification of your opinion. 

Floats are an approximation of arbitrary fixed-point numbers and in fact sometimes those _are_ used as version numbers, TeX and MetaFont being the most famous examples of programs which use arbitrary fixed-point numbers as version numbers. 

The only property we care about in working with version numbers is ordering: whether two are equal or if one is greater than another. And for this, floats are fine. Aesthetically  in my opinion `x < 2.7` is less clunky than `x < (2,7)`.

 However if uncompyle6 ever gets to the point where we need to distinguish in more detail than this, yes, the integer form of the magic number would probably be used. If you want or need to use that see `xdis.magics.magic2int()`. 

For now though, float version numbers do what they need to in this program just fine. Changing the program for this particular aesthetic displeasure is not worth the effort at the moment.

I'm sorry we disagree here.

**Closed by rocky** 2018-02-23 12:55 UTC

**Comment by KOLANICH** [comment] 2018-02-23 17:43
>sometimes those are used as version numbers

Every time reverse-engineering a binary format I run into a float version numbers I curse the format's develepers ;)

>For now though, float version numbers do what they need to in this program just fine. Changing the program for this particular aesthetic displeasure is not worth the effort at the moment.

>I'm sorry we disagree here.

completely OK.
