### ISSUE TITLE
deparse_code in eval mode doesn't always emit expressions for 'x if y else z'

### ISSUE THREAD

**Issue by DRMacIver** [rocky/python-uncompyle6#53] opened 2016-09-06 13:43 UTC
e.g. consider the following running on 2.7 (the same happens on 3.5 if you change the Python version):

```
>>> _ = deparse_code(2.7, (lambda x: (1 if x else 2)).__code__, compile_mode='eval')
if x:
    return 1
return 2
```

Despite having a compile\_mode of eval the result is not an expression but instead multiple statements. 

It's not just a lack of support for if/else expressions as the following works as expected:

```
>>> _ = deparse_code(2.7, (lambda x: (1 if x else 2) * 2).__code__, compile_mode='eval')
return (1 if x else 2) * 2
```

This was tested on uncompyle 2.8.2.

**Comment by rocky** [comment] 2016-09-06 15:15
A couple of confusions here. For interactive expressions, I think you want [compile_mode](https://docs.python.org/2/library/functions.html#compile) set to single'`.  

Second, and more seriously,  I'm not sure what you are expecting. What you are getting is looks to me, however whacky, looks correct given the way Python works: the code object, here, a lambda  contains only its body; it doesn't contain the lambda or a function signature. `1 if x else 2` is equivalent to what was reported, and that's the only thing that we attempt to provide.

**Comment by DRMacIver** [comment] 2016-09-06 15:21
> For interactive expressions, I think you want compile_mode set to single.

I don't think interactive expressions are what I want here? I'm trying to decompile lambda bodies.

> Second, and more seriously, I'm not sure what you are expecting. 

Maybe I don't understand what the compile\_mode argument is supposed to do then. I was assuming it was intended to be dual to the mode flag on compile (as per what you linked to) and thus produce something that was valid for that mode. The output here is not an expression (it's a series of statements) and thus wouldn't compile in that mode.

Is there something I should be using instead if I wanted to always get an expression out?

**Comment by rocky** [comment] 2016-09-07 00:59
What you'd do is change the code so that `expr` as the goal symbol in say https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/parsers/parse2.py#L24 rather than 'stmts'. 

The grammar could be paired down a lot since there's lots of stuff you don't need, although that's not strictly necessary.

**Comment by rocky** [comment] 2016-09-08 05:44
Closing this since this is a misunderstanding not a bug. Feel free to open another issue or revise your request.

**Closed by rocky** 2016-09-08 05:44 UTC
