### ISSUE TITLE
failure for "if a or not b:"

### ISSUE THREAD

**Issue by pfremy** [rocky/python-uncompyle6#478] opened 2023-11-11 21:39 UTC
## Description

uncompyle6 fails at this simple condition : 

    if a or not b:
         print("a or not b")

This is actually turned into : 

    if not (a or b):
        print('a or not b')

## How to Reproduce

Compile then decompile the following function : 

```
def a_or_not_b(a, b):
    if a or b:
        print('a or b')

    if a or not b:
        print('a or not b')

```
You get : 

```
def a_or_not_b(a, b):
    if a or b:
        print('a or b')
    if not (a or b):
        print('a or not b')

```
## Output Given

No specific error reported.

## Expected behavior

In this case, no surprises, it should produce code that is equivalent to the original one, even if not identical.

If a is True, in the original code, the outcome is print('a or not b'). In the compiled code, the outcome is incorrect.

If you remove the first if, you can also get an incorrect decompiling, but with a slightly different transformation.

## Environment
```

(.env) c:\work\log_enhancer>uncompyle6 --version
uncompyle6 3.9.0
(.env) c:\work\log_enhancer>python --version
Python 3.8.10

(.env) c:\work\log_enhancer>pip show xdis
Name: xdis
Version: 6.0.5
Summary: Python cross-version byte-code disassembler and marshal routines
Home-page: https://github.com/rocky/python-xdis/
Author: Rocky Bernstein, Hartmut Goebel and others
Author-email: rb@dustyfeet.com
License: GPL-2.0
Location: c:\work\log_enhancer\.env\lib\site-packages
Requires: six, click
Required-by: uncompyle6

(.env) c:\work\log_enhancer>python -c "import sys; print(sys.version)"
3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:34:34) [MSC v.1928 32 bit (Intel)]

Windows 10 Enterprise 22H2  build 19045.3570

```
## Workarounds

Not really so far. I'll check other uncompilers.

## Priority

Up to you.

**Comment by pfremy** [comment] 2023-11-11 21:41
github won't let me attach python or pyc files

**Comment by rocky** [comment] 2023-11-12 00:05
> github won't let me attach python or pyc files

Not a problem here, the report is detailed and simple enough that I can reproduce the problem. A fix for this seems pretty straightforward and I'll make this for decompyle3 which specializes in 3.7 and 3.8 bytecode.  Backporting it will be left as an exercise for a volunteer (although until the code bases are brought more in sync, details are a little different, but the same idea).

For the future to attach python and pyc files, put them both in a zip or tar.gz file.

**Closed** 2023-11-12 01:55 UTC
Labels: volunteer wanted, Python 3.8, Works on decompyle3

**Comment by pfremy** [comment] 2023-11-13 10:56
Thanks for the super quick answer. I read your comments about lack of financial support so I was not expecting this to be fixed that quickly.

I'll check the updated code. It seems to me that there are more ways if/else condition can be incorrectly decompiled. I'll report on decompyle3 for the future.

**Comment by rocky** [comment] 2023-11-13 13:05
Speed depends on a number of factors like:

*  how much thought and effort was put into the report, 
*  how well instructions for reporting a bug were followed, 
* how hard the the problem is, 
* how interested I am
* likeliness this is being used for something not quite legitimate
* whether I have time
* karma, and of course
* level of suport

**Comment by rocky** [comment] 2023-11-13 13:12
Ooops - looks like I forgot to include in decompile the commit to the code base: https://github.com/rocky/python-decompile3/commit/ed375df6b21ecbddd21cf6aaa37c7673da876751
