### ISSUE TITLE
Unknown magic number 62216

### ISSUE THREAD

**Issue by dancezarp** [rocky/python-uncompyle6#219] opened 2019-02-23 11:27 UTC
## Description

I have a Desktop Windows application to reverse engineer written in Python which seems to be packed with a tool like py2exe into a EXE file. Looking at the PYC files I gathered from the library.zip it seems that the magic number for them is 62216 F308. In order to obtain a sample of source code and bytecode I used the python27.dll and compiled this:
[bytecode.zip](https://github.com/rocky/python-uncompyle6/files/2896744/bytecode.zip)

If needed I can compile more sources and probably provide the python27.dll. The version obtained from python27.dll is: 2.7.15 (default, Jul 25 2018, 15:45:19) [MSC v.1600 32 bit (Intel)]

## How to Reproduce

```console
$ uncompyle6 <command-line-options>
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\uncompyle6.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\uncompyle6\bin\uncompile.py", line 181, in main_bin
    **options)
  File "c:\python27\lib\site-packages\uncompyle6\main.py", line 232, in main
    linemap_stream, do_fragments)
  File "c:\python27\lib\site-packages\uncompyle6\main.py", line 133, in decompile_file
    source_size) = load_module(filename, code_objects)
  File "c:\python27\lib\site-packages\xdis\load.py", line 107, in load_module
    fast_load=fast_load, get_code=get_code)
  File "c:\python27\lib\site-packages\xdis\load.py", line 136, in load_module_from_file_object
    (ord(magic[0:1])+256*ord(magic[1:2]), filename))
ImportError: Unknown magic number 62216 in site.pyc
$
```

## Environment

- Uncompyle6 version: uncompyle6 3.2.5
- Python version: Python 2.7.13
- OS: Windows 10

**Comment by rocky** [comment] 2019-02-23 13:08
If you change the magic number to a valid 2.7 magic number, you can disassemble and decompyle the bytecode. 

Here is a pro-tip for this project (but may be applicable for other projects as well). If you want help, you should read and follow the instructions on how to report a bug or that are given in the template when you opened this. 

Since you mignt not have read them fully -  I will remind that if you can't disassemble the bytecode, don't bother opening an issue here -  you will just be annoying, and I assume that is not your intent. 

Oh and this seems to be a duplicate of issue #218 that you opened yesterday.

**Closed by rocky** 2019-02-23 13:08 UTC
Labels: Python 2.7, invalid, invalid bytecode

**Comment by dancezarp** [comment] 2019-02-25 16:08
Definitely, it wasn't my intent to annoy anyone and I am sorry for not reading all the instruction given. You were right about the disassemble because I tried on another Python 2.7 and it did not work. Also by only changing the magic code uncompyle entered in an infinite loop. This got me thinking that the opcodes were not valid. After dumping the opcodes and compared them with the ones from a normal python27 they were different despite having the same version. Modified the opcodes obtained from the python27.dll to the xdis opcodes and the decompilation worked fine. 

Took me a while to figure it out but the disassembly got me on the right track.

Thank you Rocky.
