### ISSUE TITLE
discord's bot.py on  3.5 

### ISSUE THREAD

**Issue by Hyperclaw79** [rocky/python-uncompyle6#120] opened 2017-06-09 22:46 UTC
So, I've been trying to decompile the bytecode for my discord bot's bot.py. However, I'm getting a weird error as stated below:

`'charmap' codec can't encode characters in position 24811-24812: character maps to <undefined>`

Complete output:
```
> uncompyle6 version 2.10.1
> Python bytecode 3.5 (3350)
> Decompiled from: Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]
> Embedded file name: C:\Users\Harshith Thota\Desktop\Desktop\DiscordBot\HyperBot-master\Hyperbot\bot.py
> Compiled at: 2017-06-09 14:12:55
> Size of source mod 2**32: 95984 bytes
Instruction context:

 429     242  BREAK_LOOP
            243  JUMP_BACK           152  'to 152'
            246  POP_BLOCK
->        247_0  COME_FROM_LOOP           '126'
            247  JUMP_ABSOLUTE       250  'to 250'


> file bot.cpython-35.pyc
> 'charmap' codec can't encode characters in position 24811-24812: character maps to <undefined>
```

I'm also attaching the file for reference.

https://drive.google.com/open?id=0B8Z0RTw3hcQrOWRkY2tiWE44NFU

**Comment by rocky** [comment] 2017-06-09 23:24
The `file bot.cpython-35.pyc` output is not relevant and doesn't come from `uncompyle6`. Perhaps you are a frontend interface to this? 

More relevant is 
```
 429     242  BREAK_LOOP
            243  JUMP_BACK           152  'to 152'
            246  POP_BLOCK
->        247_0  COME_FROM_LOOP           '126'
```

and this is an uncompyle6 bug in running Python 3.5 bytecode. However it is in a class of control flow bugs and uncompyle6 is in great need of a rewrite on how this is handled. 

If you have the corresponding source code, I can probably help. If not, then it will eventually get fixed  in the course of bug fixing that goes on in this project. However, it may take a while since there aren't that many people working on the project.

**Comment by Hyperclaw79** [comment] 2017-06-10 01:01
Oh i see. Thanks for the reply. So looks like I'm out of options but to recode i guess.

**Comment by rocky** [comment] 2017-06-10 01:24
Well, you don't have to recode everything from scratch. Just the functions that didn't decompile. There are maybe only one or two functions that don't decompile like on_player.

**Comment by rocky** [comment] 2017-06-10 01:30
One other thing. If you have old source and compile that on 3.5 and decompile it, if you get similar sorts of errors, since you have the source there, you can whittle the problem down maybe to a particular 3.5 sequence of control flow and then maybe if that's fixed in uncompyle6 it will handle the newer version you don't have the source to.

**Comment by Hyperclaw79** [comment] 2017-06-10 02:04
I see. Sounds good. Will check it out. 👍 
` There are maybe only one or two functions that don't decompile like on_player.` Wait, how do I check that? I can't read Bytecode :/
And how can I recover the file with these exclusions? I don't recall a .py_dis file being generated tbh.

**Comment by rocky** [comment] 2017-06-10 02:36
> Wait, how do I check that? 

Well, I think you weren't running uncompyle6 directly. `uncompyle6 --help` is your friend here. 

A command you might try is `uncompyle6 -o bot.py bot.cpython-35.pyc` . When I did that I got the output here: 

https://gist.github.com/rocky/cc65ed565a2ad5bde9377667a5e2a339

**Comment by rocky** [comment] 2017-06-10 02:41
> I compiled my old source code and I found similar error.

Ok great. Now read: 

https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md#narrowing-the-problem

Because I _know_  you want to help out and not just get help.  Specifically find the function(s) that are not compiling correctly and save those to a file. compile those and then try to reduce the code by removing and simplifying python until the error goes away. Just before the error goes away, send that.

**Comment by Hyperclaw79** [comment] 2017-06-11 05:45
@rocky  Sorry for the late reply, been busy yesterday and had a bad headache.
Anyways, thanks for the decompiled source code you gave me, it was very helpful in rebuilding my bot.
I've done analysis on the code and looks like the decompiler was giving an error because of an `async` in front of the `for lmsg in self.logs_from(channel, limit=1):` in ` _on_player_play`.

**Comment by rocky** [comment] 2017-06-11 06:27
Thanks fro the information. Sorry about your headache. 

Would you please write a simple test case (the simplest one possible) that I can use to debug this and add as a test case?  If it is exactly what you say, then this shouldn't be too hard to fix, basically adding a grammar rule for this and adjusting the semantic action that gets used for the LHS nonterminal. 

I don't know how soon I can get to this, (it may not be soon). But with this fix in place if you ever have this problem again it will be a little less painful. (And others will benefit too).

**Comment by Hyperclaw79** [comment] 2017-06-11 08:31
Here, I've written a simple Testcase:

```py
import unittest

class TestBadAsyncCheck(unittest.TestCase):

  def test_bad_async(self,ch=input('Enter the command:\n')):
      if ch.startswith('async'):
          if ch.split(' ')[1] == 'def':
              res = 'Good'
          else:
              res = 'Bad'
          self.assertEqual(res,'Good')
          print('Bad async not found. Safe.')

suite = unittest.TestLoader().loadTestsFromTestCase(TestBadAsyncCheck)
unittest.TextTestRunner(verbosity=2).run(suite)
```
For integrating it into your code, just replace input() with a parameter in class definition and call it with the parameter in the main code.

The logic is that, async simply wraps a <u>function</u> with the 
```py
@asyncio.coroutine
``` 
decorator and returns a coroutine object. Since any function starts with 
```py
 def
``` 
keyword, we can just check for it.

**Comment by Hyperclaw79** [comment] 2017-06-11 08:36
Oh wait, according to PEP 492, async can be used with for as an asynchronous iterator.
https://www.python.org/dev/peps/pep-0492/#asynchronous-iterators-and-async-for

So not sure why this happened. I'll recompile and redecompile to see if I messed up somewhere.

**Comment by Hyperclaw79** [comment] 2017-06-11 09:01
@rocky Well, the `async for` is valid but the decompilation error still exists. And looks like I've encountered another error. This one is a unicode error:

`# 'charmap' codec can't encode characters in position 17325-17326: character maps to <undefined>`

I'd like to debug it but it would've been possible if I at least have the character line to work with instead of character position. 

To make matters worse, this doesn't give me the code at all in my decompiled py file. 

```py
# uncompyle6 version 2.10.1
# Python bytecode 3.5 (3350)
# Decompiled from: Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]
# Embedded file name: C:\Users\Harshith Thota\Desktop\Desktop\DiscordBot\HyperBot-master\Hyperbot\bot.py
# Compiled at: 2017-06-11 14:17:07
# Size of source mod 2**32: 88345 bytes
```
Maybe the UnicodeError exception in your code has a break instead of continue.

**Comment by rocky** [comment] 2017-06-11 09:21
This is way to complex for me to follow. Also one bug per issue please. 

Although I said "test case" I didn't intend for you to use unitest or pytest or anything like that. Just a very simple python 3.5 program like you find in test/simple_source/bugs35.

**Comment by Hyperclaw79** [comment] 2017-06-11 10:40
oh i see. I'll keep looking into it.

**Comment by gauravssnl** [comment] 2017-07-01 09:55
How can i decompile .py files in which codes are in marshal format.For example : 
import marshal, imp
if imp.get_magic() != '\x03\xf3\r\n':
    raise ImportError('wrong Python version; need Python ')
__code = marshal.loads('c\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00@\x00\x00\x00s\x80\x00\x00\x00d\x00\x00d\x01\x00l\x00\x00Z\x00\x00d\x00\x00d\x01\x00l\x01\x00Z\x01\x00d\x00\x00d\x01\x00l\x02\x00Z\x02\x00d\x02\x00Z\x03\x00d\x03\x00Z\x04\x00d\x04\x00Z\x05\x00d\x05\x00Z\x06\x00d\x06\x00Z\x07\x00d\x07\x00Z\x08\x00d\x08\x00Z\t\x00d\t\x00Z\n\x00d\n\x00\x84\x00\x00Z\x0b\x00d\x0b\x00\x84\x00\x00Z\x0c\x00e\r\x00d\x0c\x00k\x02\x00r|\x00e\x0c\x00\x83\x00\x00\x01n\x00\x00d\x01\x00S(\r\x00\x00\x00i\xff\xff\xff\xffNs\x04\x00\x00\x00\x1b[0ms\x05\x00\x00\x00\x1b[31ms\x07\x00\x00\x00\x1b[1;32ms\x05\x00\x00\x00\x1b[33ms\x05\x00\x00\x00\x1b[34ms\x05\x00\x00\x00\x1b[35ms\x05\x00\x00\x00\x1b[36ms\x05\x00\x00\x00\x1b[37mc\x01\x00\x00\x00\x02\x00\x00\x00\x04\x00\x00\x00C\x00\x00\x00sG\x00\x00\x00x@\x00|\x00\x00d\x01\x00\x17D]4\x00}\x01\x00t\x00\x00j\x01\x00j\x02\x00|\x01\x00\x83\x01\x00\x01t\x00\x00j\x01\x00j\x03\x00\x83\x00\x00\x01t\x04\x00j\x05\x00d\x02\x00d\x03\x00\x15\x83\x01\x00\x01q\x0b\x00Wd\x00\x00S(\x04\x00\x00\x00Ns\x01\x00\x00\x00\ng\x00\x00\x00\x00\x00\x00\x08@iZ\x00\x00\x00(\x06\x00\x00\x00t\x03\x00\x00\x00syst\x06\x00\x00\x00stdoutt\x05\x00\x00\x00writet\x05\x00\x00\x00flusht\x04\x00\x00\x00timet\x05\x00\x00\x00sleep(\x02\x00\x00\x00t\x01\x00\x00\x00st\x01\x00\x00\x00c(\x00\x00\x00\x00(\x00\x00\x00\x00s\x13\x00\x00\x00/mnt/sdcard/ovpn.pyt\t\x00\x00\x00slowprint\x0c\x00\x00\x00s\x08\x00\x00\x00\x00\x01\x11\x01\x10\x01\r\x01c\x00\x00\x00\x00\x02\x00\x00\x00\x04\x00\x00\x00C\x00\x00\x00s\xdf\x01\x00\x00t\x00\x00j\x01\x00d\x01\x00\x83\x01\x00\x01t\x02\x00t\x03\x00d\x02\x00d\x03\x00\x14\x17\x83\x01\x00\x01t\x00\x00j\x01\x00d\x01\x00\x83\x01\x00\x01t\x04\x00t\x05\x00d\x04\x00\x17\x83\x01\x00}\x00\x00|\x00\x00d\x05\x00k\x02\x00rn\x01t\x00\x00j\x01\x00d\x01\x00\x83\x01\x00\x01t\x02\x00t\x03\x00d\x02\x00d\x03\x00\x14\x17\x83\x01\x00\x01t\x02\x00t\x05\x00d\x06\x00\x17\x83\x01\x00\x01t\x02\x00t\x03\x00d\x02\x00d\x03\x00\x14\x17\x83\x01\x00\x01t\x06\x00j\x07\x00d\x07\x00\x83\x01\x00\x01t\x02\x00t\x05\x00d\x08\x00\x17\x83\x01\x00\x01t\x06\x00j\x07\x00d\t\x00\x83\x01\x00\x01t\x02\x00t\x08\x00d\n\x00\x17\x83\x01\x00\x01t\x06\x00j\x07\x00d\t\x00\x83\x01\x00\x01t\x04\x00t\t\x00d\x0b\x00\x17\x83\x01\x00}\x01\x00t\x02\x00t\x05\x00d\x0c\x00|\x01\x00\x16\x17\x83\x01\x00\x01t\x06\x00j\x07\x00d\t\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\r\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\x0e\x00\x83\x01\x00\x01t\x02\x00t\x08\x00d\x0f\x00\x17\x83\x01\x00\x01t\x06\x00j\x07\x00d\x07\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\x01\x00\x83\x01\x00\x01t\x02\x00t\x03\x00d\x02\x00d\x03\x00\x14\x17\x83\x01\x00\x01t\x00\x00j\x01\x00d\x01\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\x10\x00|\x01\x00\x16\x83\x01\x00\x01nm\x00|\x00\x00d\x11\x00k\x02\x00r\xac\x01t\x00\x00j\x01\x00d\x01\x00\x83\x01\x00\x01t\x02\x00t\n\x00d\x12\x00\x17\x83\x01\x00\x01t\x06\x00j\x07\x00d\t\x00\x83\x01\x00\x01t\x0b\x00\x83\x00\x00\x01n/\x00t\x00\x00j\x01\x00d\x01\x00\x83\x01\x00\x01t\x02\x00t\t\x00d\x13\x00\x17\x83\x01\x00\x01t\x06\x00j\x07\x00d\t\x00\x83\x01\x00\x01t\x0c\x00\x83\x00\x00\x01d\x00\x00S(\x14\x00\x00\x00Nt\x05\x00\x00\x00cleart\x01\x00\x00\x00#i.\x00\x00\x00s"\x00\x00\x00+ Anda yakin ingin mulai ? (y/t): t\x01\x00\x00\x00ys+\x00\x00\x00  --= NetHandlers OpenVPN Internet Free =--i\x02\x00\x00\x00s&\x00\x00\x00+ Ketik lokasi config OpenVPN berada !i\x01\x00\x00\x00s"\x00\x00\x00  Contoh: sdcard/openvpn/sg72.ovpns\x12\x00\x00\x00\n  Lokasi config: s\x12\x00\x00\x00  Import config %ss\x18\x00\x00\x00setprop net.dns1 8.8.8.8s\x18\x00\x00\x00setprop net.dns2 8.8.4.4s"\x00\x00\x00  Mengatur dns ke 8.8.8.8, 8.8.4.4s\x0c\x00\x00\x00openvpn "%s"t\x01\x00\x00\x00ts\x0f\x00\x00\x00+ Terimakasih !s&\x00\x00\x00+ Jawaban tidak benar, ulang kembali !(\r\x00\x00\x00t\x02\x00\x00\x00ost\x06\x00\x00\x00systemR\x08\x00\x00\x00t\x01\x00\x00\x00Wt\t\x00\x00\x00raw_inputt\x01\x00\x00\x00GR\x04\x00\x00\x00R\x05\x00\x00\x00t\x01\x00\x00\x00Ct\x01\x00\x00\x00Ot\x01\x00\x00\x00Bt\x04\x00\x00\x00exitt\x07\x00\x00\x00OpenVPN(\x02\x00\x00\x00t\x05\x00\x00\x00Mulait\x06\x00\x00\x00config(\x00\x00\x00\x00(\x00\x00\x00\x00s\x13\x00\x00\x00/mnt/sdcard/ovpn.pyR\x16\x00\x00\x00\x12\x00\x00\x00sD\x00\x00\x00\x00\x01\r\x01\x12\x01\r\x01\x10\x01\x0c\x01\r\x01\x12\x01\x0e\x01\x12\x01\r\x01\x0e\x01\r\x01\x0e\x01\r\x01\x10\x01\x12\x01\r\x01\r\x01\r\x01\x0e\x01\r\x01\r\x01\x12\x01\r\x01\x14\x01\x0c\x01\r\x01\x0e\x01\r\x01\n\x02\r\x01\x0e\x01\r\x01t\x08\x00\x00\x00__main__(\x0e\x00\x00\x00R\r\x00\x00\x00R\x00\x00\x00\x00R\x04\x00\x00\x00R\x0f\x00\x00\x00t\x01\x00\x00\x00RR\x11\x00\x00\x00R\x13\x00\x00\x00R\x14\x00\x00\x00t\x01\x00\x00\x00PR\x12\x00\x00\x00t\x02\x00\x00\x00GRR\x08\x00\x00\x00R\x16\x00\x00\x00t\x08\x00\x00\x00__name__(\x00\x00\x00\x00(\x00\x00\x00\x00(\x00\x00\x00\x00s\x13\x00\x00\x00/mnt/sdcard/ovpn.pyt\x08\x00\x00\x00<module>\x01\x00\x00\x00s\x18\x00\x00\x00$\x02\x06\x01\x06\x01\x06\x01\x06\x01\x06\x01\x06\x01\x06\x01\x06\x02\t\x06\t%\x0c\x01')
del marshal, imp
exec __code
del __code
Is decompiling this possible or not???Please,tell me how @rocky

**Comment by rocky** [comment] 2017-07-02 11:02
@gauravssnl I am pretty sure you can get what you want done, but this isn't the right place or venue to ask for help. Instead [StackOverflow][http://stackoverflow.com] is a better place. 

If I see the question there, I'll try to answer it. (The solution involves you more understanding what's going on, and this is _also_ not the right place for discussion and answers. In github issue trackers one reports bugs and feature. It is most likely not a bug and _might_ not be about changing the existing code either, but rather how to use what is there.) 

So posting to something like on SO, if I don't get around to someone else may see it and address. (In fact if this had been done yesterday, perhaps someone would have answered it when I couldn't). And whatever solution comes of this,  others will be more likely to benefit from in the future.

In sum, there's a reason that given thought and doing things the right way is a good idea.

**Comment by gauravssnl** [comment] 2017-07-02 13:02
i am sorry for that.i wanted to ask you personally,but i did not find your Twitter/FB profile.So,i asked you here .I really do not know how to decompile that.can you guide me how to decompile it,please???
i will be thankful to you if you do me this favour . @rocky

**Closed** 2017-09-17 20:21 UTC
Labels: control flow, Python 3.5, unresponsive user
