### ISSUE TITLE
2.7: Cannot uncompyle very large files of dictionaries

### ISSUE THREAD

**Issue by dontech** [rocky/python-uncompyle6#238] opened 2019-05-14 12:58 UTC
## Description

Very large files with large dictionaries fail to uncompyle.

## How to Reproduce

1) Generate code with the follow shell script:

```
echo "values = {" > test.py
for i in {1..100000}
do
echo "'value$i' : $i+1," >> test.py
done
echo "}" >> test.py

```

2) Compile code.

3) Uncompyle. This ends with:

`Parse error at or near `STORE_MAP' instruction at offset 917506`

## Environment

Cygwin - CYGWIN_NT-10.0 CPHAPF1J07AX 3.0.6(0.338/5/3) 2019-04-06 16:18 x86_64 Cygwin
Python - Python 2.7.16 (default, Mar 20 2019, 12:15:19)

Thanks,

/pedro

**Comment by rocky** [comment] 2019-05-14 13:06
This is a duplicate of #188 

There will probably always be a limitation. However if you'd like to work on this and suggest a fix, by all means do!

**Closed by rocky** 2019-05-14 13:06 UTC

**Comment by dontech** [comment] 2019-05-14 13:28
I am not sure this is a duplicate. As long as it completes i would be more than happy.
The other bug does not seem to indicate that it crashes.

**Comment by rocky** [comment] 2019-05-14 13:42
I've added a note that #188 can also cause a crash.
